pipeline {
    agent none
    stages {
        stage('Build') {
            agent any
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }

    stage('Confirm Deploy') {
      steps {
        input(message: 'Okay to deploy to staging?', ok: 'Yes')
      }
        stage('Test') {
            agent any
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            
        }
        stage('Deliver') {
            agent any
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
            // post {
            //     success {
            //         archiveArtifacts 'dist/add2vals'
            //     }
            // }
        }
    }
}
